### ISSUE TITLE
Implementeer roxygen

### ISSUE THREAD

**Issue by HJWesteneng** [UMCUneuro/MRI#2]
Documentation is one of the most important aspects of good code.

Zie voor introductie:
https://cran.r-project.org/web/packages/roxygen2/vignettes/roxygen2.html

**Comment by HHGTan** [comment]
Ha @HJWesteneng 
De mappen zijn herstructureerd naar package structuur: in de R/ directory staan alleen objects, oftewel functions en definitions. Het cleaningscript is verplaatst naar de Scripts/ directory.

Roxygen is bij deze geïmplementeerd. Mocht je ook de functies willen documenteren, dan kan je beginnen met: `devtools::load_all()`. En als je je documentatie wil laten opslaan gebruik je `roxygen2::roxygenise()`.
Als de functies zijn bijgewerkt kunnen we deze issue ook sluiten :)

**Comment by HJWesteneng** [comment]
Ha @HHGTan 
Super! Ik was gisteravond de hele avond aan het braken :-( dus heb ik nog niet in detail naar kunnen kijken. Klinkt iig heel goed. Als alles werkt kun je wat mij betreft deze issue sluiten.

**Comment by HHGTan** [comment]
Oei dat klinkt niet goed. Beterschap Henk-Jan!
