### ISSUE TITLE
Wide2long

### ISSUE THREAD

**Issue by HJWesteneng** [UMCUneuro/MRI#3]
Soms staat data in Progeny in "wide" format terwijl het longitudinale data betreft. Het best analyseerbare format voor longitudinale data is een "long" format. Doel: generiek script maken voor omzetten van "wide" longitudinale data naar "long" longitudinale data. Waarschijnlijk is het niet mogelijk dat de computer zelf herkent bij welke variabelen het om "wide" format longitudinale data gaat. Indien dit inderdaad het geval blijkt te zijn, dit als "human input" toevoegen in /Data/Format_v1.xlsx, bijv. in de kolom Wide2long. Andere (beter interpreteerbare) formats zijn uiteraard ook welkom. @HHGTan: wil jij dit oppakken?

**Comment by harold** [comment]
99% sure I'm not the Harold you're looking for. hth.

**Comment by HJWesteneng** [comment]
Sorry, I was indeed looking for another Harold. I have changed it.

**Comment by HHGTan** [comment]
I'm on it. Ik ga even kijken wat de mogelijkheden zijn om wide formats te herkennen. Zo niet dan moeten we het inderdaad specificeren. Ik hou je op de hoogte

**Comment by HJWesteneng** [comment]
Super. Ik probeer dit weekend even een nieuwe commt te doen zodat alles op to date is.

**Comment by HHGTan** [comment]
Ha @HJWesteneng, 

Ik heb misschien een plan om bv longitudinale data in wide format te herkennen.

1. Begin met het maken van een matrix voor de 'string distance' tussen alle kolomnamen.
Dit kan bv met de functie adist. --> adist("ECAS datum FU1", "ECAS datum FU2") geeft bv een waarde van 1 omdat 1 character verschillend is.

2. Groepeer de bijpassende kolommen obv korte string distance. 
Dit zou met een bepaalde afkapwaarde kunnen, bv maximaal 3 characters verschil.
Hopelijk zou je dan dit soort groepen overhouden:
Groep 1: "DoECAS1", "DoECAS2", "DoECAS3" etc
Groep 2: "ECAS_Total1", "ECAS_Total2", "ECAS_Total2" etc
Groep 3: "ALSFTDQ_Total1", "ALSFTDQ_Total2" etc

3. Kijk bij elk van de gevonden kolommen of er een overeenkomende string is (bv "ECAS") en kijk of deze matcht met de "Group" kolom in de Format_v1.xlsx

4. Zo ja, dan kan de conversie naar long format makkelijk met Tidyr gedaan worden.

Is deze gedachtenstroom een beetje te volgen? Ik hoor graag of je nog tips of opmerkingen hebt.

**Comment by HHGTan** [comment]
Oh en zou je me nog kunnen toevoegen als collaborator?
Dan kan ik meteen branches aanmaken op deze repository:)

**Comment by HJWesteneng** [comment]
Ha @HHGTan 

Dat is inderdaad een goed idee! Er zijn wel een paar kanttekeningen die het uiteindelijk mogelijk best moeilijk maken:
1. Waarschijnlijk moet je het uiteindelijk toepassen op een combinatie van originele namen en rename's (zie object rename1 in script).
2. Mogelijk zijn datums irritant, DoB en DoO kunnen bijvoorbeeld een kleine adist hebben maar gaan over verschillende zaken. Je zou de originele naam van dit soort variabelen eerst door gsub("Date of", "", var, ignore.case = TRUE) heen kunnen trekken.

Ik heb hieronder vast een opzetje gemaakt. Volgens mij is de opbouw van "wide" longitudinale data vaak als volgt: `^.*\\:.*|^.*\\:\\s.*`, waarbij je t/m `\\:` of `\\:\\s` eigenlijk wilt verwijderen. Als je dat gedaan hebt komt er nog een moeilijkheid, namelijk dat wat je overhoudt niet altijd uniform is maar soms van allerlei leestekens e.d. voorzien is. Dit kun je ip weghalen door alle interpunctie te gsubben. Zie hieronder wat code:

```
test1 <- c('ALSnummer #', 'Sex (gender at birth)', 'Date of birth', 'Date of onset',
           'Date of diagnosis', 'Date of Death', 'AFLOOP: Datum check', 'Diagnosis',
           'Site of Onset', 'ECAS: Date of testing', 'FU2: ECAS: Date of testing',
           'FU3: ECAS: Date of testing', 'FU4: ECAS: Date of testing',
           'FU5: ECAS: Date of testing', 'ECAS: Version A or B', 'FU2 ECAS: Version A or B',
           'FU3 ECAS: Version A or B', 'FU4 ECAS: Version A or B', 'FU5 ECAS: Version A or B',
           'Reat or write problems', 'FU2: Read or write problems', 'FU3: Read or write problems',
           'FU4: Read or write problems', 'FU5: Read or write problems', 'ECAS ALS_SPECIFIC',
           'FU2: ECAS ALS_SPECIFIC', 'FU3: ECAS ALS_SPECIFIC', 'FU4: ECAS ALS_SPECIFIC',
           'FU5: ECAS ALS_SPECIFIC', 'ECAS ALS_NONSPECIFIC', 'FU2: ECAS ALS_NONSPECIFIC',
           'FU3: ECAS ALS_NONSPECIFIC', 'FU4: ECAS ALS-NONSPECIFIC', 'FU5: ECAS ALS_NONSPECIFIC',
           'ECAS_Total_Score', 'FU2: ECAS Total score', 'FU3: ECAS Total score',
           'FU4: ECAS Total score', 'FU5: ECAS Total score')
test2 <- gsub("^.*\\:|^.*\\:\\s", "", test1)
test3 <- gsub("[[:punct:]]", " ", test2)
adist(test3)
```

Daarna kun je op de uitkomst van adist de rest van de cleaning doen. Ip zou een adist van 0 dan groepsdata moeten pakken. Vervolgens zou ik denk ik naar group in format1.xlsx kijken om het weer te bundelen (script moet wel snel error geven als het niet exact klopt). Je zou iets vergelijkbaars kunnen maken voor renames zodat er een soort dubbelcheck ontstaat

Het bovenstaande is mogelijk niet hufterproof maar het is iig een eerste stap.

Overigens zie ik zojuist dat dit uiteraard geen typefouten in Progeny zoals "Reat or write problems" dekt... :-).

Tenslotte is het misschien nog een idee om aan Bas te vragen of hij een file heeft met de titels van alle variabelen in Progeny. Je kunt dan mogelijk makkelijker patronen herkennen voor longitudinale data (die in wide staat) en mogelijk moet het patroon wat ik aan het begin aangegeven heb dan nog aangepast worden. Of misschien wil je group uit format1 toevoegen aan iedere colname voordat je adist runt (dus in het voorbeeld hierboven bijv. `test3 <- paste0(group, "_", test3)` waarbij group uiteraard een corresponderende string moet zijn). Deze laatste actie voorkomt dat als je bijv. van de ECAS een variabele "version" hebt en dit ook van de ALSFTD_Q hebt, dat ze dan als hetzelfde herkent worden.

**Comment by HHGTan** [comment]
Ha @HJWesteneng ,

Ik heb nu een script gemaakt die na renaming de kolomnamen groepeert zonder ook maar iets over de kolomnamen te zeggen.
Het groeperen van variabelen zoals "doECAS[1-5]" en "ECAS_total [1-5]" gaat eigenlijk heel goed. 
Het herkennen van 'supergroepen' zoals "ECAS" lukt ook aardig. ALS supergroepen herkent hij op dit moment "ECAS", "ECAS_" en "o" (de laatste komt bv van DoO, SoO etc) 

Mijn idee was om dit te fuzzy greppen (met agrep) uit de group kolom in de format1.xlsx tabel
Als dit een match is dan kan hij alle variabelen uit de supergroep converten en als dit geen match is dan doet hij niks. 

Ik zal vandaag de laatste stappen proberen te implementeren. De vraag is even of we dit met agrep moeten doen (nadeel: wat onvoorspelbaar gedrag) of met adist (nadeel: arbitraire waarde), maar ik hou je op de hoogte.

Mocht je alvast een blik willen werpen, dan kan je het script vinden op de wide2long branch

**Comment by HHGTan** [comment]
Het is ondertussen gelukt.
Ik ga nog even reformatten en een extra check inbouwen.
Daarna zie je een pull request verschijnen.

**Comment by HJWesteneng** [comment]
@HHGTan Super! Ik kan niet wachten om het te testen :-). Werkt het ip voor al dit soort wide2long variabelen of alleen voor ECAS data? En kun je misschien op dit issue nog een kleine beschrijving van de stappen geven die je gevolgd hebt (puntsgewijs) zodat we daar later nog op terug kunnen grijpen?

**Comment by HHGTan** [comment]
Zeker, zie hier de summary (overgenomen uit de pull request)

Wide2Long summary:
1. Groepeer op adist =< 1
2. Kijk van elke groep wat de common string is = subgroep
3. Kijk of er common strings zijn tussen alle subgroepen = supergroep
4. Kijk of de supergroep daadwerkelijk in format1.xlsx onder Group staat
5. Voor elke supergroep waar punt 4 waar is, wordt een long format tabel gemaakt.

**Comment by HJWesteneng** [comment]
Namen variabelen die wide2long data zijn moet altijd een getal bevatten (bijv. DoECAS1, DoECAS2 etc.). Dit nu ook geïmplementeerd in script.

**Comment by HHGTan** [comment]
Update: wide2long_revisited.
1. Verbeterde functies toegevoegd voor het vinden van de langste gemeenschappelijke substring.
2. Gewogen superstring selectie obv stringlengte^2 * frequentie
